# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(choices=[('1', 'Mumbai'), ('2', 'Delhi')], max_length=1)),
                ('services', models.CharField(choices=[('1', 'Nursing'), ('2', 'Equipment')], max_length=1)),
                ('no_of_hours', models.IntegerField()),
                ('deposits', models.IntegerField()),
                ('rent_or_purchase', models.CharField(choices=[('1', 'Rent'), ('2', 'Purchase')], max_length=1)),
            ],
        ),
    ]
