# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='deposits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='no_of_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rent_or_purchase',
            field=models.CharField(choices=[('1', 'Rent'), ('2', 'Purchase')], max_length=1, null=True),
        ),
    ]
